name: build_test_push
on: 
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    name: Unittests
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t metocean/opendrift:${GITHUB_REF#refs/*/} .
      - name: Run tests OpenDrift
        run: docker run --rm metocean/opendrift:${GITHUB_REF#refs/*/} pytest /source/opendrift/tests
      - name: Docker push
        run: docker push metocean/opendrift:${GITHUB_REF#refs/*/}